"""Tests for routers/audit.py's read/filter/paginate surface over rows written
by app/middleware/audit.py. Real audit rows are generated by making actual
mutating requests through the test client (the middleware writes them as a
side effect), rather than inserting AuditLog rows by hand — this also
exercises the middleware's own entity_type/entity_id extraction end to end.
RBAC (401/403/200 for ADMIN-only) is already covered by test_api_permissions.py
and test_rbac_regression.py; this file focuses on filtering/pagination/shape.
"""
from __future__ import annotations

from tests.conftest import auth_headers


def _property_payload(**overrides) -> dict:
    payload = {
        "property_code": "PRP-AUDIT-001",
        "name": "נכס לבדיקת יומן ביקורת",
        "address": "רחוב הבדיקה 1",
        "region": "מרכז",
        "latitude": 32.08,
        "longitude": 34.78,
        "asset_type": "OFFICE_BUILDING",
        "replacement_value": 1_000_000,
        "book_value": 800_000,
    }
    payload.update(overrides)
    return payload


def test_list_audit_log_captures_create_and_update_actions(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)

    created = client.post("/api/properties", json=_property_payload(), headers=headers).json()
    client.put(f"/api/properties/{created['property_id']}", json={"name": "שם מעודכן"}, headers=headers)

    resp = client.get("/api/audit-log", headers=headers)
    assert resp.status_code == 200
    body = resp.json()
    actions = [(e["entity_type"], e["action"]) for e in body["entries"]]
    assert ("PROPERTIES", "CREATE") in actions
    assert ("PROPERTIES", "UPDATE") in actions


def test_list_audit_log_orders_most_recent_first(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)

    client.post("/api/properties", json=_property_payload(property_code="PRP-A"), headers=headers)
    client.post("/api/properties", json=_property_payload(property_code="PRP-B"), headers=headers)

    resp = client.get("/api/audit-log", headers=headers)
    entries = resp.json()["entries"]
    timestamps = [e["timestamp"] for e in entries]
    assert timestamps == sorted(timestamps, reverse=True)
    # The most recent create (PRP-B) must appear before the older one (PRP-A).
    log_ids_by_new_value_order = [e["log_id"] for e in entries]
    assert log_ids_by_new_value_order == sorted(log_ids_by_new_value_order, reverse=True)


def test_list_audit_log_filters_by_entity_type_case_insensitively(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    client.post("/api/properties", json=_property_payload(), headers=headers)

    resp = client.get("/api/audit-log", params={"entity_type": "properties"}, headers=headers)
    assert resp.status_code == 200
    assert all(e["entity_type"] == "PROPERTIES" for e in resp.json()["entries"])
    assert len(resp.json()["entries"]) >= 1


def test_list_audit_log_filters_by_action(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    created = client.post("/api/properties", json=_property_payload(), headers=headers).json()
    client.put(f"/api/properties/{created['property_id']}", json={"name": "עדכון"}, headers=headers)

    resp = client.get("/api/audit-log", params={"action": "update"}, headers=headers)
    assert resp.status_code == 200
    assert all(e["action"] == "UPDATE" for e in resp.json()["entries"])


def test_list_audit_log_filters_by_user_id_and_resolves_user_name(client, make_user):
    admin = make_user(role="ADMIN", full_name="מנהל הבדיקה")
    headers = auth_headers(admin)
    client.post("/api/properties", json=_property_payload(), headers=headers)

    resp = client.get("/api/audit-log", params={"user_id": admin.user_id}, headers=headers)
    entries = resp.json()["entries"]
    assert len(entries) >= 1
    assert all(e["user_id"] == admin.user_id for e in entries)
    assert entries[0]["user_name"] == "מנהל הבדיקה"


def test_list_audit_log_filters_by_entity_id(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    p1 = client.post("/api/properties", json=_property_payload(property_code="PRP-X"), headers=headers).json()
    p2 = client.post("/api/properties", json=_property_payload(property_code="PRP-Y"), headers=headers).json()
    client.put(f"/api/properties/{p1['property_id']}", json={"name": "a"}, headers=headers)
    client.put(f"/api/properties/{p2['property_id']}", json={"name": "b"}, headers=headers)

    resp = client.get("/api/audit-log", params={"entity_id": p1["property_id"]}, headers=headers)
    entries = resp.json()["entries"]
    assert len(entries) >= 1
    assert all(e["entity_id"] == p1["property_id"] for e in entries)


def test_list_audit_log_pagination_limit_and_offset(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    for i in range(5):
        client.post("/api/properties", json=_property_payload(property_code=f"PRP-{i}"), headers=headers)

    page1 = client.get("/api/audit-log", params={"limit": 2, "offset": 0}, headers=headers).json()
    page2 = client.get("/api/audit-log", params={"limit": 2, "offset": 2}, headers=headers).json()

    assert len(page1["entries"]) == 2
    assert len(page2["entries"]) == 2
    assert page1["total"] == page2["total"]
    assert page1["total"] >= 5
    page1_ids = {e["log_id"] for e in page1["entries"]}
    page2_ids = {e["log_id"] for e in page2["entries"]}
    assert page1_ids.isdisjoint(page2_ids)


def test_list_audit_log_rejects_limit_over_500(client, make_user):
    admin = make_user(role="ADMIN")
    resp = client.get("/api/audit-log", params={"limit": 501}, headers=auth_headers(admin))
    assert resp.status_code == 422


def test_list_audit_log_rejects_zero_limit(client, make_user):
    admin = make_user(role="ADMIN")
    resp = client.get("/api/audit-log", params={"limit": 0}, headers=auth_headers(admin))
    assert resp.status_code == 422


def test_list_audit_log_rejects_negative_offset(client, make_user):
    admin = make_user(role="ADMIN")
    resp = client.get("/api/audit-log", params={"offset": -1}, headers=auth_headers(admin))
    assert resp.status_code == 422


def test_list_audit_log_default_limit_caps_at_50(client, make_user):
    admin = make_user(role="ADMIN")
    resp = client.get("/api/audit-log", headers=auth_headers(admin))
    assert resp.status_code == 200
    assert resp.json()["limit"] == 50


def test_list_audit_log_date_range_excludes_out_of_range_rows(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    client.post("/api/properties", json=_property_payload(), headers=headers)

    resp = client.get(
        "/api/audit-log",
        params={"date_from": "2099-01-01T00:00:00", "date_to": "2099-12-31T23:59:59"},
        headers=headers,
    )
    assert resp.status_code == 200
    assert resp.json()["entries"] == []


def test_list_audit_log_empty_for_unknown_entity_type(client, make_user):
    admin = make_user(role="ADMIN")
    resp = client.get(
        "/api/audit-log", params={"entity_type": "NOT_A_REAL_ENTITY"}, headers=auth_headers(admin)
    )
    assert resp.status_code == 200
    assert resp.json()["entries"] == []


def test_entity_types_returns_distinct_sorted_values(client, make_user):
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    client.post("/api/properties", json=_property_payload(property_code="PRP-Z1"), headers=headers)
    client.post("/api/properties", json=_property_payload(property_code="PRP-Z2"), headers=headers)

    resp = client.get("/api/audit-log/entity-types", headers=headers)
    assert resp.status_code == 200
    types = resp.json()
    assert "PROPERTIES" in types
    assert len(types) == len(set(types))  # distinct
    assert types == sorted(types)


def test_get_endpoint_does_not_write_its_own_audit_row(client, make_user):
    """GETs are explicitly excluded from auditing (module docstring) — reading
    the audit log itself must not create new entries, or every call would
    grow the log forever."""
    admin = make_user(role="ADMIN")
    headers = auth_headers(admin)
    before = client.get("/api/audit-log", headers=headers).json()["total"]
    client.get("/api/audit-log", headers=headers)
    after = client.get("/api/audit-log", headers=headers).json()["total"]
    assert before == after
