"""email read receipts

Revision ID: 0dd04377c435
Revises: a4d6f1c8e3b7
Create Date: 2026-08-22 22:52:48.442886

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged the
usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs DateTime
rendering on existing datetime columns, FK constraint "removed"/"added" pairs that
are the same constraint under a different autogenerated name, and indexes that
exist in sql/schema.sql but aren't mirrored as `Index(...)`/`index=True` in
models.py) — none of that is a real schema change, so it's stripped out here. Only
the two new columns (TODO_SPEC.md "משימה 19") remain: Email_Recipients.read_at
and Emails.read_receipt_requested.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0dd04377c435'
down_revision: Union[str, Sequence[str], None] = 'a4d6f1c8e3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adds Email_Recipients.read_at (nullable — NULL means "not read yet";
    set once, the first time is_read flips True, never cleared on unread; see
    models.EmailRecipient's docstring) and Emails.read_receipt_requested
    (NOT NULL, server_default='0' so every existing row backfills to "not
    requested" rather than NULL, matching the column's Python-side
    default=False in models.py — see models.Email's docstring for why this
    only gates the receipt *UI*, not whether read_at gets tracked)."""
    op.add_column('Email_Recipients', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('Emails', sa.Column('read_receipt_requested', sa.Boolean(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Drops the two read-receipt columns."""
    op.drop_column('Emails', 'read_receipt_requested')
    op.drop_column('Email_Recipients', 'read_at')
