"""baseline: current schema (matches sql/schema.sql)

Revision ID: 5d5363142853
Revises:
Create Date: 2026-08-20 15:28:48.678411

This is a deliberate no-op, not the literal `alembic revision --autogenerate` output.
The real `RiskDB` schema was created by `sql/schema.sql` (see CLAUDE.md — schema.sql is
the authoritative DDL, run once via `sqlcmd -i sql/schema.sql`), and this project has
been evolving `models.py` + `schema.sql` together by hand ever since (see every
"✅ בוצע" entry in TODO_SPEC.md stage 1). This revision exists purely so Alembic has a
starting point to build *future* migrations on top of — `alembic stamp head` marks it
as already applied without running anything against a real database.

The autogenerated diff (kept here only as a comment, not executed) consisted entirely
of noise from comparing `models.py`'s generic SQLAlchemy types against SQL Server's own
rendering of them, plus indexes that exist in schema.sql but aren't mirrored as
SQLAlchemy `Index(...)` declarations in models.py:
  - DATETIME2() vs DateTime(): the same physical column type — DateTime already
    compiles to DATETIME2 on the mssql dialect; autogenerate just diffs the two
    Python-side type objects, not the actual generated SQL.
  - TINYINT() vs SmallInteger(): Asset_Risk_Profiles' risk-score columns are declared
    SmallInteger() in models.py (see CLAUDE.md's Unicode/UnicodeText gotcha for why
    generic types matter) but schema.sql narrowed them to TINYINT at the DDL level;
    both hold 1-5 risk scores fine, no data-shape difference.
  - "removed" indexes (IX_RiskProfiles_Property, IX_AuditLog_Entity, IX_Claims_*, ...):
    real indexes schema.sql already created for query performance, just not declared
    via `index=True` / `Index(...)` in models.py — running the autogenerated
    `op.drop_index(...)` calls would have actually deleted them. Left alone here;
    a future migration that changes one of these tables should add an explicit
    `op.create_index(...)` (and the matching `Index(...)`/`index=True` in models.py)
    rather than silently dropping what's already there.
"""
from __future__ import annotations

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5d5363142853'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op: see module docstring. A fresh environment should still run
    `sqlcmd -i sql/schema.sql` (per CLAUDE.md) rather than `alembic upgrade head` to
    stand up the schema from scratch — this revision is the migration *chain's*
    starting point, not a schema-creation script in its own right."""
    pass


def downgrade() -> None:
    """No-op — see upgrade()."""
    pass
