"""entity emails table

Revision ID: a3f7c1e9d4b6
Revises: f65d3748905b
Create Date: 2026-08-22 13:05:00.000000

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged
the usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs
DateTime rendering on existing datetime columns, FK constraint
"removed"/"added" pairs that are the same constraint under a different
autogenerated name, and indexes that exist in sql/schema.sql but aren't
mirrored as `Index(...)`/`index=True` in models.py) — none of that is a real
schema change, so it's stripped out here. Only the new Entity_Emails table
(TODO_SPEC.md "משימה 11" step 1) remains.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a3f7c1e9d4b6'
down_revision: Union[str, Sequence[str], None] = 'f65d3748905b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Entity_Emails — links an email thread (keyed by its thread-root
    email_id, see models.EntityEmail's docstring) to an Incident/Claim/Property."""
    op.create_table('Entity_Emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Unicode(length=20), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_by', sa.BigInteger(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('auto_linked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['Emails.email_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', 'entity_type', 'entity_id', name='uq_entity_emails_email_entity')
    )
    op.create_index('IX_EntityEmails_Entity', 'Entity_Emails', ['entity_type', 'entity_id'], unique=False)


def downgrade() -> None:
    """Drop Entity_Emails."""
    op.drop_index('IX_EntityEmails_Entity', table_name='Entity_Emails')
    op.drop_table('Entity_Emails')
