"""user auto-responder settings

Revision ID: a4d6f1c8e3b7
Revises: e1b4c7a9d3f5
Create Date: 2026-08-22 16:20:00.000000

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged the
usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs DateTime
rendering on existing datetime columns, FK constraint "removed"/"added" pairs that
are the same constraint under a different autogenerated name, and indexes that
exist in sql/schema.sql but aren't mirrored as `Index(...)`/`index=True` in
models.py) — none of that is a real schema change, so it's stripped out here. Only
the four new Users columns (TODO_SPEC.md "משימה 18" step 1) remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a4d6f1c8e3b7'
down_revision: Union[str, Sequence[str], None] = 'e1b4c7a9d3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adds Users.auto_reply_enabled/auto_reply_start/auto_reply_end/auto_reply_body
    (out-of-office / auto-responder settings — see models.User's docstring).
    auto_reply_enabled gets server_default='0' so every existing row backfills to
    "disabled" rather than NULL, matching the column's NOT NULL + Python-side
    default=False in models.py."""
    op.add_column('Users', sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('auto_reply_start', sa.Date(), nullable=True))
    op.add_column('Users', sa.Column('auto_reply_end', sa.Date(), nullable=True))
    op.add_column('Users', sa.Column('auto_reply_body', sa.UnicodeText(), nullable=True))


def downgrade() -> None:
    """Drops the four out-of-office columns."""
    op.drop_column('Users', 'auto_reply_body')
    op.drop_column('Users', 'auto_reply_end')
    op.drop_column('Users', 'auto_reply_start')
    op.drop_column('Users', 'auto_reply_enabled')
