"""email scheduled send

Revision ID: b66e5e16401b
Revises: c33576291f9f
Create Date: 2026-08-22 17:11:55.669160

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged
the same fixed set of cosmetic diffs against the live DB every prior
migration in this repo has hit (DATETIME2 vs DateTime rendering on every
existing datetime column, TINYINT vs SmallInteger on Asset_Risk_Profiles'
risk-score columns, FK constraint "removed"/"added" pairs that are the same
constraint under a different autogenerated name, the EncryptedString vs plain
NVARCHAR rendering on the two already-encrypted columns, and indexes that
exist in sql/schema.sql but aren't mirrored as `Index(...)`/`index=True` in
models.py) — none of that is a real schema change, so it's stripped out here.
Only the two new nullable columns on Emails (TODO_SPEC.md "משימה 13":
`scheduled_for`, `scheduled_recipients` — see app/models.py's Email
docstring) remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b66e5e16401b'
down_revision: Union[str, Sequence[str], None] = 'c33576291f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adds Emails.scheduled_for (future send time for status='SCHEDULED'
    rows) and Emails.scheduled_recipients (JSON-serialized intended
    to/cc/bcc, until the message actually sends and gets real
    Email_Recipients rows — see services/email.py's schedule_email)."""
    op.add_column('Emails', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('Emails', sa.Column('scheduled_recipients', sa.UnicodeText(), nullable=True))


def downgrade() -> None:
    """Drops both columns."""
    op.drop_column('Emails', 'scheduled_recipients')
    op.drop_column('Emails', 'scheduled_for')
