"""email templates table

Revision ID: c33576291f9f
Revises: a3f7c1e9d4b6
Create Date: 2026-08-22 16:43:13.245856

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged
the usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs
DateTime rendering on existing datetime columns, TINYINT vs SmallInteger on
Asset_Risk_Profiles' risk-score columns, FK constraint "removed"/"added"
pairs that are the same constraint under a different autogenerated name, the
EncryptedString vs plain NVARCHAR rendering on two already-encrypted columns,
and indexes that exist in sql/schema.sql but aren't mirrored as
`Index(...)`/`index=True` in models.py) — none of that is a real schema
change, so it's stripped out here. Only the new Email_Templates table
(TODO_SPEC.md "משימה 12" step 1) remains.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c33576291f9f'
down_revision: Union[str, Sequence[str], None] = 'a3f7c1e9d4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Email_Templates — reusable canned messages for the Compose modal
    (subject_template/body_template may contain {{variable}} placeholders,
    substituted client-side; see app/routers/email_templates.py's docstring)."""
    op.create_table('Email_Templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('subject_template', sa.Unicode(length=500), nullable=False),
    sa.Column('body_template', sa.UnicodeText(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Drop Email_Templates."""
    op.drop_table('Email_Templates')
