"""labels and email_labels tables

Revision ID: d8a1c4f6b2e9
Revises: 8594395c58b2
Create Date: 2026-08-22 14:20:00.000000

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged
the usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs
DateTime rendering on existing datetime columns, FK constraint
"removed"/"added" pairs that are the same constraint under a different
autogenerated name, and indexes that exist in sql/schema.sql but aren't
mirrored as `Index(...)`/`index=True` in models.py) — none of that is a real
schema change, so it's stripped out here. Only the new Labels/Email_Labels
tables (TODO_SPEC.md "משימה 16" steps 1-2) remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd8a1c4f6b2e9'
down_revision: Union[str, Sequence[str], None] = '8594395c58b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Labels (per-user tags) and Email_Labels (the thread<->label join
    table, keyed off the thread-root email_id — see models.EmailLabel's
    docstring)."""
    op.create_table('Labels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('color', sa.Unicode(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('IX_Labels_User', 'Labels', ['user_id'], unique=False)

    op.create_table('Email_Labels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['Emails.email_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['Labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id', 'label_id', name='uq_email_labels_email_label')
    )
    op.create_index('IX_EmailLabels_Email', 'Email_Labels', ['email_id'], unique=False)
    op.create_index('IX_EmailLabels_Label', 'Email_Labels', ['label_id'], unique=False)


def downgrade() -> None:
    """Drop Email_Labels then Labels (children before parents)."""
    op.drop_index('IX_EmailLabels_Label', table_name='Email_Labels')
    op.drop_index('IX_EmailLabels_Email', table_name='Email_Labels')
    op.drop_table('Email_Labels')
    op.drop_index('IX_Labels_User', table_name='Labels')
    op.drop_table('Labels')
