"""email rules table

Revision ID: e1b4c7a9d3f5
Revises: d8a1c4f6b2e9
Create Date: 2026-08-22 15:10:00.000000

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged
the usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs
DateTime rendering on existing datetime columns, FK constraint
"removed"/"added" pairs that are the same constraint under a different
autogenerated name, and indexes that exist in sql/schema.sql but aren't
mirrored as `Index(...)`/`index=True` in models.py) — none of that is a real
schema change, so it's stripped out here. Only the new Email_Rules table
(TODO_SPEC.md "משימה 17" step 1) remains.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e1b4c7a9d3f5'
down_revision: Union[str, Sequence[str], None] = 'd8a1c4f6b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Email_Rules (per-user "if condition(s) then action(s)" auto-filters —
    see models.EmailRule's docstring for the JSON-text conditions/actions
    convention)."""
    op.create_table('Email_Rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('conditions', sa.UnicodeText(), nullable=False),
    sa.Column('actions', sa.UnicodeText(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('IX_EmailRules_User', 'Email_Rules', ['user_id'], unique=False)


def downgrade() -> None:
    """Drop Email_Rules."""
    op.drop_index('IX_EmailRules_User', table_name='Email_Rules')
    op.drop_table('Email_Rules')
