"""email system tables

Revision ID: f65d3748905b
Revises: b7e4d1a930c8
Create Date: 2026-08-22 12:17:44.257701

Hand-trimmed per CLAUDE.md: `alembic revision --autogenerate` also re-flagged the
usual fixed set of cosmetic diffs against the live DB (DATETIME2 vs DateTime
rendering on ~15 existing datetime columns, TINYINT vs SmallInteger on
Asset_Risk_Profiles' risk scores, a batch of FK constraint "removed"/"added" pairs
that are the same constraint under a different autogenerated name, and every index
that exists in sql/schema.sql but isn't mirrored as an `Index(...)`/`index=True` in
models.py) — none of that is a real schema change, so it's stripped out here. Only
the three new email tables (Task 1 of TODO_SPEC.md) remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f65d3748905b'
down_revision: Union[str, Sequence[str], None] = 'b7e4d1a930c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create Emails, Email_Attachments, Email_Recipients (in FK-safe order)."""
    op.create_table('Emails',
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.Unicode(length=500), nullable=False),
    sa.Column('body_html', sa.UnicodeText(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['Emails.email_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('Email_Attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Unicode(length=500), nullable=False),
    sa.Column('file_name', sa.Unicode(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Unicode(length=100), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['Emails.email_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Email_Recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_type', sa.Unicode(length=10), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('folder', sa.Unicode(length=20), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['Emails.email_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Drop the three email tables (children before parents)."""
    op.drop_table('Email_Recipients')
    op.drop_table('Email_Attachments')
    op.drop_table('Emails')
